# docker-compose.yml
services:
  namenode1:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.3-java8
    container_name: nn1
    environment:
      - CLUSTER_NAME=localhdfs
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_replication=2
      - HDFS_CONF_dfs_namenode_name_dir=/hdfs/namenode
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"    # Namenode Web UI
      - "9820:9820"    # Namenode IPC
      - "8020:8020"   # Namenode RPC
    volumes:
      - ./data/nn:/hdfs/namenode
      - ./conf/hdfs-site.xml:/opt/hadoop-3.1.3/etc/hadoop/hdfs-site.xml:ro
      - ./conf/core-site.xml:/opt/hadoop-3.1.3/etc/hadoop/core-site.xml:ro
  namenode2:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.3-java8
    container_name: nn2
    environment:
      - CLUSTER_NAME=localhdfs
      - CORE_CONF_fs_defaultFS=hdfs://namenode2:8020
      - HDFS_CONF_dfs_replication=2
      - HDFS_CONF_dfs_namenode_name_dir=/hdfs/nn2
      - CORE_CONF_fs_defaultFS=hdfs://namenode2:8020
    ports:
      - "9871:9870"    # Namenode Web UI
      - "9821:9820"    # Namenode IPC
      - "8021:8020"   # Namenode RPC
    volumes:
      - ./data/nn2:/hdfs/nn2
      - ./conf/hdfs-site.xml:/opt/hadoop-3.1.3/etc/hadoop/hdfs-site.xml:ro
      - ./conf/core-site.xml:/opt/hadoop-3.1.3/etc/hadoop/core-site.xml:ro

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.3-java8
    container_name: dn1
    depends_on:
      - namenode1
      - namenode2
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_datanode_data_dir=/hdfs/datanode
    volumes:
      - ./data/dn1:/hdfs/datanode
      - ./conf/hdfs-site.xml:/opt/hadoop-3.1.3/etc/hadoop/hdfs-site.xml:ro
      - ./conf/core-site.xml:/opt/hadoop-3.1.3/etc/hadoop/core-site.xml:ro

  client:
    image: maven:3.8.6-openjdk-11
    container_name: hdfs-client
    working_dir: /workspace/java-client
    volumes: 
      - ./javaApiHdfs/hdfsUtils:/workspace/java-client
    depends_on:
      - namenode1
      - namenode2
      - datanode1
    tty: true
    entrypoint: ["tail", "-f", "/dev/null"]
    stdin_open: true

networks:
  hadoop-net:
    driver: bridge