apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: hdfs-dn-failure
  namespace: chaos-mesh
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: hdfs
      role: datanode
  duration: "1m"
